

double Get_CName_Alt(int i);
double Get_CName_Azm(int i);
void CalculateCNames();
CString Get_CString(int i);

void CalculateOutlines();
double Get_Outlines_Alt(int i);
double Get_Outlines_Azm(int i);

void CalculateStars(int starlimit);
double Get_Star_Alt(int i);
double Get_Star_Azm(int i);
int Get_Star_Mag(int i);


void CalculateMess();
double Get_Mess_Alt(int i);
double Get_Mess_Azm(int i);
CString Get_Mess_String(int i);
