//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ViewMark1.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_VIEWMARK1TYPE               129
#define IDB_BITMAP1                     130
#define IDS_STRING130                   130
#define IDD_WHERE_DIALOG                132
#define IDD_WHEN_DIALOG                 133
#define IDB_BITMAP2                     134
#define IDD_SETTINGS_DIALOG             135
#define IDD_SEARCH_DIALOG               138
#define IDD_GOTO_ALTAZ_DIALOG           139
#define IDD_GOTO_RADEC_DIALOG           140
#define IDD_KEY_DIALOG                  141
#define IDD_DATA_DIALOG                 142
#define IDD_AUTO_DIALOG                 143
#define IDD_UPDATE_DIALOG               146
#define IDB_BITMAP4                     167
#define IDB_BITMAP3                     169
#define IDB_BITMAP5                     171
#define IDB_BITMAP6                     173
#define IDB_BITMAP7                     183
#define IDB_BITMAP8                     188
#define IDR_TOOLBAR                     189
#define IDB_BITMAP9                     194
#define IDD_TOOLBOX_DIALOG              195
#define IDD_VERT_SCROLL_DIALOG          197
#define IDD_DIALOG_JOVIAN               199
#define IDD_KEY_DEFINE                  200
#define IDD_GOTO_MESS                   201
#define IDB_BUTTON2                     204
#define IDC_SPIN_LONG_DEG               1006
#define IDC_LONG_BOX_DEG                1007
#define IDC_LONG_BOX_MIN                1008
#define IDC_SPIN_DAY                    1010
#define IDC_SPIN_LONG_MIN               1010
#define IDC_SPIN_MONTH                  1011
#define IDC_LONG_BOX_SEC                1011
#define IDC_SPIN_YEAR                   1012
#define IDC_SPIN_LONG_SEC               1012
#define IDC_YEAR_BOX                    1013
#define IDC_LAT_BOX_SEC                 1013
#define IDC_DAY_BOX                     1014
#define IDC_SPIN_LAT_SEC                1014
#define IDC_MONTH_BOX                   1015
#define IDC_LAT_BOX_MIN                 1015
#define IDC_TIME_SEC                    1016
#define IDC_SPIN_LAT_MIN                1017
#define IDC_SPIN_SEC                    1017
#define IDC_LAT_BOX_DEG                 1018
#define IDC_TIME_MIN                    1018
#define IDC_SPIN_LAT_DEG                1019
#define IDC_SPIN_MIN                    1019
#define IDC_TIME_HOUR                   1020
#define IDC_SPIN_HOUR                   1021
#define IDC_TIME_TZ                     1022
#define IDC_SPIN_TZ                     1023
#define IDC_TIME_DL                     1024
#define IDC_SPIN_DL                     1025
#define IDC_CHECK2                      1028
#define IDC_CHECK_HORIZON               1028
#define IDC_CHECK3                      1029
#define IDC_RADIO1                      1029
#define IDC_CHECK_PLANETS               1029
#define IDC_RADIO_SUN                   1029
#define IDC_RADIO_DAY                   1029
#define IDC_RADIO_LOOK                  1029
#define IDC_CHECK4                      1030
#define IDC_RADIO2                      1030
#define IDC_CHECK_STARS                 1030
#define IDC_GOTO_ALT_DEG                1030
#define IDC_RADIO_VENUS                 1030
#define IDC_RADIO_SEC                   1030
#define IDC_RADIO_ZOOM                  1030
#define IDC_CHECK5                      1031
#define IDC_RADIO3                      1031
#define IDC_GOTO_ALT_MIN                1031
#define IDC_CHECK_SITES                 1031
#define IDC_RADIO_MOON                  1031
#define IDC_RADIO_HOUR                  1031
#define IDC_RADIO_TIME                  1031
#define IDC_CHECK6                      1032
#define IDC_RADIO4                      1032
#define IDC_GOTO_ALT_SEC                1032
#define IDC_RADIO_MERCURY               1032
#define IDC_CHECK_INVERT                1032
#define IDC_RADIO_MIN                   1032
#define IDC_CHECK7                      1033
#define IDC_RADIO5                      1033
#define IDC_GOTO_AZ_DEG                 1033
#define IDC_RADIO_MARS                  1033
#define IDC_CHECK_MARKERS               1033
#define IDC_RADIO_MONTH                 1033
#define IDC_CHECK8                      1034
#define IDC_RADIO6                      1034
#define IDC_GOTO_AZ_MIN                 1034
#define IDC_RADIO_URANUS                1034
#define IDC_RADIO_YEAR                  1034
#define IDC_CHECK_PARALLAX              1034
#define IDC_CHECK9                      1035
#define IDC_RADIO7                      1035
#define IDC_GOTO_AZ_SEC                 1035
#define IDC_RADIO_JUPITER               1035
#define IDC_CHECK_LABELS                1035
#define IDC_RADIO8                      1036
#define IDC_SPIN_GOTO_ALT_DEG           1036
#define IDC_RADIO_SATURN                1036
#define IDC_CHECK_DETAILS               1036
#define IDC_RADIO9                      1037
#define IDC_SPIN_GOTO_ALT_MIN           1037
#define IDC_RADIO_NEPTUNE               1037
#define IDC_CHECK_MESS                  1037
#define IDC_RADIO10                     1038
#define IDC_SPIN_GOTO_ALT_SEC           1038
#define IDC_RADIO_PLUTO                 1038
#define IDC_CHECK_HIDE                  1038
#define IDC_SPIN_GOTO_AZ_DEG            1039
#define IDC_CHECK_SM                    1039
#define IDC_SPIN_GOTO_AZ_MIN            1040
#define IDC_CHECK_OUTLINE               1040
#define IDC_GOTO_RA_DEG                 1041
#define IDC_GOTO_RA_HOUR                1041
#define IDC_CHECK_REALSIZE              1041
#define IDC_SPIN_GOTO_RA_DEG            1042
#define IDC_SPIN_GOTO_RA_HOUR           1042
#define IDC_CHECK_GRID                  1042
#define IDC_GOTO_RA_MIN                 1043
#define IDC_CHECK_HOURGLASS             1043
#define IDC_SPIN_GOTO_RA_MIN            1044
#define IDC_GOTO_RA_SEC                 1045
#define IDC_SPIN_GOTO_RA_SEC            1046
#define IDC_GOTO_DEC_HOUR               1047
#define IDC_GOTO_DEC_DEG                1047
#define IDC_SPIN_GOTO_DEC_HOUR          1048
#define IDC_SPIN_GOTO_DEC_DEG           1048
#define IDC_GOTO_DEC_MIN                1049
#define IDC_SPIN_GOTO_DEC_MIN           1050
#define IDC_GOTO_DEC_SEC                1051
#define IDC_SPIN_DEC_SEC                1052
#define IDC_SPIN_GOTO_DEC_SEC           1052
#define IDC_BODY_NAME                   1053
#define IDC_EDIT_JUMP                   1055
#define IDC_SPIN_JUMP                   1056
#define IDC_EDIT_DELAY                  1057
#define IDC_SPIN_DELAY                  1058
#define IDC_LIST_UNIT                   1060
#define IDC_LIST_LOCK                   1061
#define IDC_COMBO_HOW                   1061
#define IDC_COMBO_WHO                   1062
#define IDC_EDIT_JUMP_VALUE             1063
#define IDC_SPIN_JUMPVALUE              1064
#define IDC_EDIT_DELAY_VALUE            1065
#define IDC_COMBO_MAGNITUDES            1065
#define IDC_SPIN_DELAYVALUE             1066
#define IDC_TAB1                        1066
#define IDC_NORTH_OR_SOUTH              1082
#define IDC_EAST_OR_WEST                1083
#define IDC_SPIN_GOTO_AZ_SEC            1083
#define IDC_COMBO_LOCATION              1085
#define IDC_COMBO_WHERE                 1086
#define IDC_BUTTON_NORTH_SOUTH          1087
#define IDC_BUTTON_EAST_WEST            1088
#define IDC_VSCROLLBAR                  1091
#define IDC_SCROLLBAR2                  1097
#define IDC_SLIDER                      1099
#define IDC_SLIDER_ZOOM                 1101
#define IDC_CHECK_TIP                   1102
#define IDC_TOP_TIP                     1103
#define IDC_CHECK_DAYLIGHT              1104
#define IDC_MESS_NUMBER                 1107
#define IDC_SPIN_MESS_NUMBER            1108
#define IDC_BUTTON2                     1110
#define ID_CONTROL_ZOOM_IN              32771
#define ID_CONTROL_ZOOM_OUT             32772
#define ID_CONTROL_LOOK_UP              32773
#define ID_CONTROL_LOOK_DOWN            32774
#define ID_CONTROL_LOOK_LEFT            32775
#define ID_CONTROL_LOOK_RIGHT           32776
#define ID_CONTROL_LOCATION             32777
#define IDD_HOW_DIALOG                  32778
#define IDD_FIND_DIALOG                 32780
#define ID_CONTROL_TIME_NOW             32781
#define ID_CONTROL_TIME_AUTO            32782
#define ID_CONTROL_SET_AUTO             32794
#define ID_CONTROL_TIME_PLUS            32797
#define ID_CONTROL_TIME_MINUS           32798
#define IDD_TOOL_DIALOG                 32799
#define ID_TASK_PLANETS                 32800
#define ID_TASK_INVERT                  32801
#define ID_TASK_STARS                   32802
#define ID_TASK_AUTOTIME                32803
#define ID_CONTROL_DELETE               32804
#define ID_CONTOL_SAVE                  32805
#define ID_TASK_OUTLINES                32806
#define ID_BUTTON32812                  32812
#define ID_BUTTON32813                  32813
#define ID_BUTTON32814                  32814
#define ID_BUTTON32815                  32815
#define ID_BUTTON32816                  32816
#define IDD_COMPASS                     32818
#define ID_TASK_MESS                    32822
#define ID_TASK_LABELS                  32823
#define ID_MENU_JUPITER                 32824
#define ID_CONTROL_LOOK_NORTH           32826
#define ID_CONTROL_LOOK_SOUTH           32827
#define ID_CONTROL_LOOK_EAST            32828
#define ID_CONTROL_LOOK_WEST            32829
#define ID_CONTROL_LOOK_ZENITH          32830
#define ID_CONTROL_LOOK_HORIZON         32831
#define ID_ACCEL32832                   32832
#define ID_CONTROL_TOOLBOX              32833
#define IDD_GOTO_MESS_DIALOG            32835

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        205
#define _APS_NEXT_COMMAND_VALUE         32836
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
