//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PocketUniversePro.rc
//
#define IDD_ABOUTBOX                    100
#define IDI_AppIcon                     102
#define IDI_FileIcon                    103
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_STAR1                130
#define IDB_BITMAP_STAR2                131
#define IDB_BITMAP_STAR3                132
#define IDD_WHERE_DIALOG                132
#define IDB_BITMAP_STAR4                133
#define IDB_BITMAP_STAR5                134
#define IDB_BITMAP_STAR6                135
#define IDD_SETTINGS_DIALOG             135
#define IDB_BITMAP_STAR7                136
#define IDB_BITMAP_MOON                 137
#define IDD_SEARCH_DIALOG               138
#define IDD_DIALOG_TIMEDATE             139
#define IDD_WHEN_TIMEDATE               139
#define IDD_GOTO_RADEC_DIALOG           140
#define IDD_KEY_DIALOG                  141
#define IDD_UPDATE_DIALOG               146
#define IDR_TOOLBAR                     189
#define IDD_TOOLBOX_DIALOG              195
#define IDD_GOTO_ALTAZ_DIALOG           196
#define IDD_DIALOG_JOVIAN               199
#define IDB_BITMAP11                    202
#define IDD_DIALOG_EPHEMERIS            209
#define IDB_BITMAP_BIGMOON              209
#define IDC_CHECK_DAYLIGHT              1000
#define IDC_SPIN_HOUR                   1002
#define IDC_SPIN_HOUR2                  1002
#define IDC_SPIN_MIN                    1003
#define IDC_SPIN_MIN2                   1003
#define IDC_TIME_SEC                    1004
#define IDC_TIME_HOUR2                  1005
#define IDC_TIME_MIN                    1006
#define IDC_SPIN_LONG_DEG               1006
#define IDC_DAY_BOX                     1007
#define IDC_LONG_BOX_DEG                1007
#define IDC_MONTH_BOX                   1008
#define IDC_LONG_BOX_MIN                1008
#define IDC_YEAR_BOX                    1009
#define IDC_SPIN_SEC                    1010
#define IDC_SPIN_LONG_MIN               1010
#define IDC_SPIN_DAY2                   1010
#define IDC_SPIN_DAY                    1011
#define IDC_LONG_BOX_SEC                1011
#define IDC_SPIN_MONTH2                 1011
#define IDC_SPIN_MONTH                  1012
#define IDC_SPIN_LONG_SEC               1012
#define IDC_SPIN_YEAR2                  1012
#define IDC_SPIN_YEAR                   1013
#define IDC_LAT_BOX_SEC                 1013
#define IDC_TIME_YEAR                   1013
#define IDC_SPIN_HOUR7                  1014
#define IDC_SPIN_LAT_SEC                1014
#define IDC_TIME_DAY                    1014
#define IDC_LAT_BOX_MIN                 1015
#define IDC_TIME_MONTH                  1015
#define IDC_SPIN_LAT_MIN                1017
#define IDC_SPIN_SEC2                   1017
#define IDC_LAT_BOX_DEG                 1018
#define IDC_SPIN_LAT_DEG                1019
#define IDC_TIME_HOUR                   1020
#define IDC_TIME_TZ                     1022
#define IDC_SPIN_TZ                     1023
#define IDC_CHECK_HORIZON               1028
#define IDC_CHECK_PLANETS               1029
#define IDC_CHECK_STARS                 1030
#define IDC_GOTO_ALT_DEG                1030
#define IDC_CHECK_SITES                 1031
#define IDC_GOTO_ALT_MIN                1031
#define IDC_CHECK_INVERT                1032
#define IDC_GOTO_ALT_SEC                1032
#define IDC_CHECK_MARKERS               1033
#define IDC_GOTO_AZ_DEG                 1033
#define IDC_CHECK_PARALLAX              1034
#define IDC_GOTO_AZ_MIN                 1034
#define IDC_CHECK_LABELS                1035
#define IDC_GOTO_AZ_SEC                 1035
#define IDC_CHECK_DETAILS               1036
#define IDC_SPIN_GOTO_ALT_DEG           1036
#define IDC_CHECK_MESS                  1037
#define IDC_SPIN_GOTO_ALT_MIN           1037
#define IDC_CHECK_HIDE                  1038
#define IDC_SPIN_GOTO_ALT_SEC           1038
#define IDC_CHECK_SM                    1039
#define IDC_SPIN_GOTO_AZ_DEG            1039
#define IDC_CHECK_OUTLINE               1040
#define IDC_SPIN_GOTO_AZ_MIN            1040
#define IDC_CHECK_REALSIZE              1041
#define IDC_GOTO_RA_HOUR                1041
#define IDC_CHECK_GRID                  1042
#define IDC_SPIN_GOTO_RA_HOUR           1042
#define IDC_CHECK_HOURGLASS             1043
#define IDC_GOTO_RA_MIN                 1043
#define IDC_SPIN_GOTO_RA_MIN            1044
#define IDC_CHECK_MOONGFX               1045
#define IDC_GOTO_RA_SEC                 1045
#define IDC_CHECK_ECLIPTIC              1046
#define IDC_SPIN_GOTO_RA_SEC            1046
#define IDC_GOTO_DEC_DEG                1047
#define IDC_SPIN_GOTO_DEC_DEG           1048
#define IDC_GOTO_DEC_MIN                1049
#define IDC_SPIN_GOTO_DEC_MIN           1050
#define IDC_GOTO_DEC_SEC                1051
#define IDC_SPIN_GOTO_DEC_SEC           1052
#define IDC_COMBO_HOW                   1061
#define IDC_COMBO_WHO                   1062
#define IDC_EDIT_JUMP_VALUE             1063
#define IDC_SPIN_JUMPVALUE              1064
#define IDC_EDIT_DELAY_VALUE            1065
#define IDC_COMBO_MAGNITUDES            1065
#define IDC_SPIN_DELAYVALUE             1066
#define IDC_SPIN_GOTO_AZ_SEC            1083
#define IDC_COMBO_WHERE                 1086
#define IDC_BUTTON_NORTH_SOUTH          1087
#define IDC_BUTTON_EAST_WEST            1088
#define IDC_TIME_DAYLIGHT               1104
#define IDC_MESS_NUMBER                 1107
#define IDC_SPIN_MESS_NUMBER            1108
#define IDC_COMBO_GOTOSOLAR             1109
#define IDC_ZOOM_SLIDER                 1110
#define IDC_COMBO_GOTOSTAR              1110
#define IDC_BUTTON_NORTH                1111
#define IDC_COMBO_GOTOCONST             1111
#define IDC_BUTTON_SOUTH                1112
#define IDC_BUTTON_WEST                 1113
#define IDC_BUTTONUP                    1114
#define IDC_BUTTONDOWN                  1115
#define IDC_STRING_DATE                 1115
#define IDC_BUTTONLEFT                  1116
#define IDC_RADIO_RED                   1116
#define IDC_BUTTONRIGHT                 1117
#define IDC_RADIO_CONTRAST              1117
#define IDC_JOVE_TIME_PLUS              1117
#define IDC_STRING_SUN                  1117
#define IDC_BUTTON_EAST                 1118
#define IDC_RADIO_STANDARD              1118
#define IDC_JOVE_TIME_MINUS             1118
#define IDC_STRING_MOON                 1118
#define IDC_BUTTON_TIMEMINUS            1119
#define IDC_STRING_VENUS                1119
#define IDC_BUTTON_TIMEPLUS             1120
#define IDC_STRING_MARS                 1120
#define IDC_BUTTON_ZOOMOUT              1121
#define IDC_STRING_JUPITER              1121
#define IDC_BUTTON_ZOOMIN               1122
#define IDC_STRING_SATURN               1122
#define IDC_STRING_URANUS               1123
#define IDC_STRING_NEPTUNE              1124
#define IDC_STRING_PLUTO                1125
#define IDC_STRING_USER                 1126
#define IDC_STRING_MERCURY              1127
#define IDC_STRING_MOONPHASE            1128
#define ID_MENU_SETTIMEDATE             32771
#define ID_MENU_DISPLAY                 32772
#define IDD_HOW_DIALOG                  32778
#define IDD_FIND_DIALOG                 32780
#define ID_TASK_PLANETS                 32800
#define ID_TASK_INVERT                  32801
#define ID_TASK_STARS                   32802
#define ID_TASK_AUTOTIME                32803
#define ID_TASK_OUTLINES                32806
#define ID_TASK_MESS                    32822
#define ID_TASK_LABELS                  32823
#define ID_BUTTON_GOTOMOON              32836
#define ID_BUTTON_GOTOSUN               32837
#define ID_BUTTON_GOTO_MERC             32840
#define ID_BUTTON_GOTO_VENUS            32841
#define ID_BUTTON_GOTO_MARS             32842
#define ID_BUTTON_GOTO_JUPITER          32843
#define ID_BUTTON_GOTO_SATURN           32844
#define ID_TASK_SUNMOON                 32845
#define ID_BUTTON32846                  32846
#define ID_TASK_GRID                    32847

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
